### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zyl2014888** [zhaoxingfeng/RandomForest#4]
您好，能解释一下housing.txt里CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
这个标头都是什么意思嘛？
万分感谢！

**Comment by zhaoxingfeng** [comment]
详见https://archive.ics.uci.edu/ml/machine-learning-databases/housing/，housing.names里边有字段详细解释

**Comment by zyl2014888** [comment]
非常感谢您的解答------------------ 原始邮件 ------------------
发件人: "zhaoxingfeng"<notifications@github.com>
发送时间: 2019年10月18日(星期五) 下午3:09
收件人: "zhaoxingfeng/RandomForest"<RandomForest@noreply.github.com>;
抄送: "zyl2014888"<279751705@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhaoxingfeng/RandomForest] Question (#4)



详见https://archive.ics.uci.edu/ml/machine-learning-databases/housing/，housing.names里边有字段详细解释
 
&mdash;

**Comment by zyl2014888** [comment]
<img width="740" alt="DD324DB7-71E9-4001-BBCF-35FC711EA38A" src="https://user-images.githubusercontent.com/56614725/67256140-4462db80-f4b8-11e9-92e8-fdf8798787ad.png">
您好这里有点问题,有的时候会出现这种情况

**Comment by zyl2014888** [comment]
Traceback (most recent call last):
  File "/Users/macbook/Desktop/Python/机器学习实验/RandomForestClassification.py", line 194, in <module>
    testWine()
  File "/Users/macbook/Desktop/Python/机器学习实验/RandomForestClassification.py", line 161, in testWine
    decisionTree = createTree(baggingData, bagginglabels)
  File "/Users/macbook/Desktop/Python/机器学习实验/RandomForestClassification.py", line 106, in createTree
    myTree[bestFeature]['>' + str(bestSplitValue)] = createTree(rightData, newFeatures)
  File "/Users/macbook/Desktop/Python/机器学习实验/RandomForestClassification.py", line 105, in createTree
    myTree[bestFeature]['<' + str(bestSplitValue)] = createTree(leftData, newFeatures)
  File "/Users/macbook/Desktop/Python/机器学习实验/RandomForestClassification.py", line 102, in createTree
    newFeatures, leftData, rightData = splitData(dataSet, bestFeatureIndex, features, bestSplitValue)
  File "/Users/macbook/Desktop/Python/机器学习实验/RandomForestClassification.py", line 81, in splitData
    if dt[featIndex] <= value:
TypeError: '<=' not supported between instances of 'float' and 'NoneType'

**Comment by zhaoxingfeng** [comment]
这些代码是针对python2.7写的，python3不保证有没有问题。你的环境是python3吗

**Comment by zyl2014888** [comment]
是的，3.7而且这个bug不是每次训练都有，具体原因我还没排查出来------------------ 原始邮件 ------------------
发件人: "zhaoxingfeng"<notifications@github.com>
发送时间: 2019年10月22日(星期二) 晚上7:04
收件人: "zhaoxingfeng/RandomForest"<RandomForest@noreply.github.com>;
抄送: "zyl2014888"<279751705@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhaoxingfeng/RandomForest] Question (#4)



这些代码是针对python2.7写的，python3不保证有没有问题。你的环境是python3吗
 
&mdash;

**Comment by zyl2014888** [comment]
老哥，还有个问题，您这个决策树作剪枝处理了吗？

**Comment by zhaoxingfeng** [comment]
只做了预剪枝，没有做后剪枝

**Comment by yuchensi** [comment]
KeyError: "['MEDV'] not in index"这个请问怎么解决啊，是版本问题么
